name: ESUG web site build

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ecstatic_build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y libasound2:i386 libssl1.1:i386 libfreetype6:i386

    - uses: actions/checkout@v4
      
    - name: Generate
      run: make generate

    - uses: actions/upload-artifact@v4
      with:
        name: ecstatic_site
        path: |
          _site
          !path/**/*.pillar
        retention-days: 5
        
        
  agenda_build:
   uses: pillar-markup/Microdown-Agenda/.github/workflows/main.yml@main
   with:
     agenda_filename: 2024-Conference/agenda-workshop.md;2024-Conference/agenda.md;2023-Conference/agenda.md;2023-Conference/agenda-workshop.md;2022-Conference/agenda.md;2022-Conference/agenda-workshop.md
  
    
  deploy:
    runs-on: ubuntu-latest
    needs: [ecstatic_build, agenda_build]
    
    steps:
    # needed by JamesIves/github-pages-deploy-action
    - uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v4
      with:
        path: _site
        merge-multiple: true

    - name: debug
      run: ls -R

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
      if: github.event_name != 'pull_request'
